# Source: cluster-api-aws/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: 40d5bba5-948f-4edb-b1f8-b03a6b49cd49
  namespace: 40d5bba5-948f-4edb-b1f8-b03a6b49cd49
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: 40d5bba5-948f-4edb-b1f8-b03a6b49cd49
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "40d5bba5-948f-4edb-b1f8-b03a6b49cd49-control-plane"
