---
apiVersion: v1
kind: Namespace
metadata:
  name: 40d5bba5-948f-4edb-b1f8-b03a6b49cd49
  labels:
    name: 40d5bba5-948f-4edb-b1f8-b03a6b49cd49
    # It bring the secret 'dacapod-argocd-config' using kubed
    decapod-argocd-config: enabled

