---
# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 40d5bba5-948f-4edb-b1f8-b03a6b49cd49-capi-aws
  namespace: 40d5bba5-948f-4edb-b1f8-b03a6b49cd49
  labels:
    helm.sh/chart: cluster-api-aws-0.5.0
    app.kubernetes.io/name: cluster-api-aws
    app.kubernetes.io/instance: cluster-api-aws
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
